### ISSUE TITLE
跟不上df的工作了，出的比我学的快

### ISSUE THREAD

**Issue by Hammer-888** [yunqing-me/WatermarkDM#2]

**Comment by Middle-Night** [comment]
你好，我有几个问题想请教你。1.为什么使用哦个训练水印编码器/解码器命令的时候，无法读取到指定目录下的所有图片信息2.在训练数据中嵌入二进制水印字符串的命令里，参数与py文件的参数对应不上呢

**Comment by yunqing-me** [comment]
Thank you for your interest in our work. Let me reply to your questions soon.

**Comment by yunqing-me** [comment]
> 你好，我有几个问题想请教你。1.为什么使用哦个训练水印编码器/解码器命令的时候，无法读取到指定目录下的所有图片信息
2.在训练数据中嵌入二进制水印字符串的命令里，参数与py文件的参数对应不上呢

Thank you for your interest in our work. To address your issue, could you please provide necessary steps to reproduce the errors?

Thanks.

**Comment by Middle-Night** [comment]
尊敬的作者，您好！
感谢您的回复！
我最近拜读您的论文《A Recipe for Watermarking Diffusion Models》，并在实验项目代码的时候，遇到一点问题想咨询您一下
1.第一张图片，输入命令行后，显示50000张图片计算出来的数据量为782，这个数字（可能我那个步骤不对）不知道得出来的是否正确。
2.第二张图片，命令行里的“bit length”参数无法识别。项目readme文件中说可能需要几个小时训练时间，但是我这边训练时间半小时就自动结束，而且结果未知。
3.第三张图片，命令行里的参数，与指定的python文件的参数，似乎对应不上，且强制修改命令行参数为指定python文件参数后，会被第四张图片里给定的路径覆盖掉。


以上就是我目前的项目进度以及遇到的问题，如能回答，不胜感激！





Mr.Z
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yunqing-me/WatermarkDM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月28日(星期三) 下午4:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yunqing-me/WatermarkDM] 跟不上df的工作了，出的比我学的快 (Issue #2)





  
你好，我有几个问题想请教你。1.为什么使用哦个训练水印编码器/解码器命令的时候，无法读取到指定目录下的所有图片信息
 2.在训练数据中嵌入二进制水印字符串的命令里，参数与py文件的参数对应不上呢
  
Thank you for your interest in our work. To address your issue, could you please provide necessary steps to reproduce the errors?
 
Thanks.

**Comment by yunqing-me** [comment]
你好，对于你的问题：

1. 是正常的。为了加速计算FID Score, 50K real CIFAR-10 images的statistics会被提前计算并存在一个`.npz` file里面。50K images会以`batch_size=64`进行读取，所以一共会有`50k/64=782`个batch。
2. `bit_length` [是一个预定义的`args`](https://github.com/yunqing-me/WatermarkDM/blob/368ab5893722e86ee6ce35ba556f7137897e701c/string2img/train_cifar10.py#L16)，应该是没有问题的。
3. 谢谢指出，这个地方已经解决，请查看update。

**Comment by yunqing-me** [comment]
> 尊敬的作者，您好！ 感谢您的回复！ 我最近拜读您的论文《A Recipe for Watermarking Diffusion Models》，并在实验项目代码的时候，遇到一点问题想咨询您一下 1.第一张图片，输入命令行后，显示50000张图片计算出来的数据量为782，这个数字（可能我那个步骤不对）不知道得出来的是否正确。 2.第二张图片，命令行里的“bit length”参数无法识别。项目readme文件中说可能需要几个小时训练时间，但是我这边训练时间半小时就自动结束，而且结果未知。 3.第三张图片，命令行里的参数，与指定的python文件的参数，似乎对应不上，且强制修改命令行参数为指定python文件参数后，会被第四张图片里给定的路径覆盖掉。 以上就是我目前的项目进度以及遇到的问题，如能回答，不胜感激！ Mr.Z ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yunqing-me/WatermarkDM" ***@***.***&gt;; 发送时间:&nbsp;2023年6月28日(星期三) 下午4:33 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [yunqing-me/WatermarkDM] 跟不上df的工作了，出的比我学的快 (Issue #2) 你好，我有几个问题想请教你。1.为什么使用哦个训练水印编码器/解码器命令的时候，无法读取到指定目录下的所有图片信息 2.在训练数据中嵌入二进制水印字符串的命令里，参数与py文件的参数对应不上呢 Thank you for your interest in our work. To address your issue, could you please provide necessary steps to reproduce the errors? Thanks. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;


你好，对于你的问题：

1. 是正常的。为了加速计算FID Score, 50K real CIFAR-10 images的statistics会被提前计算并存在一个`.npz` file里面。50K images会以`batch_size=64`进行读取，所以一共会有`50k/64=782`个batch。
2. `bit_length` [是一个预定义的`args`](https://github.com/yunqing-me/WatermarkDM/blob/368ab5893722e86ee6ce35ba556f7137897e701c/string2img/train_cifar10.py#L16)，应该是没有问题的。
3. 谢谢指出，这个地方已经解决，请查看update。

**Comment by Middle-Night** [comment]
感谢您为我解惑，您的回复给我极大的帮助！
祝您科研、事业一帆风顺！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月28日(周三) 下午5:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yunqing-me/WatermarkDM] 跟不上df的工作了，出的比我学的快 (Issue #2)




  
尊敬的作者，您好！ 感谢您的回复！ 我最近拜读您的论文《A Recipe for Watermarking Diffusion Models》，并在实验项目代码的时候，遇到一点问题想咨询您一下 1.第一张图片，输入命令行后，显示50000张图片计算出来的数据量为782，这个数字（可能我那个步骤不对）不知道得出来的是否正确。 2.第二张图片，命令行里的“bit length”参数无法识别。项目readme文件中说可能需要几个小时训练时间，但是我这边训练时间半小时就自动结束，而且结果未知。 3.第三张图片，命令行里的参数，与指定的python文件的参数，似乎对应不上，且强制修改命令行参数为指定python文件参数后，会被第四张图片里给定的路径覆盖掉。 以上就是我目前的项目进度以及遇到的问题，如能回答，不胜感激！ Mr.Z @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yunqing-me/WatermarkDM" @.&gt;; 发送时间:&nbsp;2023年6月28日(星期三) 下午4:33 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [yunqing-me/WatermarkDM] 跟不上df的工作了，出的比我学的快 (Issue #2) 你好，我有几个问题想请教你。1.为什么使用哦个训练水印编码器/解码器命令的时候，无法读取到指定目录下的所有图片信息 2.在训练数据中嵌入二进制水印字符串的命令里，参数与py文件的参数对应不上呢 Thank you for your interest in our work. To address your issue, could you please provide necessary steps to reproduce the errors? Thanks. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
你好，对于你的问题：
  
是正常的。为了加速计算FID Score, 50K real CIFAR-10 images的statistics会被提前计算并存在一个.npz file里面。50K images会以batch_size=64进行读取，所以一共会有50k/64=782个batch。
 
bit_length 是一个预定义的args，应该是没有问题的。
 
谢谢指出，这个地方已经解决，请查看update。

**Comment by xbtzpx** [comment]
> 感谢您为我解惑，您的回复给我极大的帮助！ 祝您科研、事业一帆风顺！
> [...](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年6月28日(周三) 下午5:33 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [yunqing-me/WatermarkDM] 跟不上df的工作了，出的比我学的快 (Issue #2) 尊敬的作者，您好！ 感谢您的回复！ 我最近拜读您的论文《A Recipe for Watermarking Diffusion Models》，并在实验项目代码的时候，遇到一点问题想咨询您一下 1.第一张图片，输入命令行后，显示50000张图片计算出来的数据量为782，这个数字（可能我那个步骤不对）不知道得出来的是否正确。 2.第二张图片，命令行里的“bit length”参数无法识别。 项目readme文件中说可能需要几个小时训练时间，但是我这边训练时间半小时就自动结束，而且结果未知。 3.第三张图片，命令行里的参数，与指定的python文件的参数，似乎对应不上，且强制修改命令行参数为指定python文件参数后，会被第四张图片里给定的路径覆盖掉。 以上就是我目前的项目进度以及遇到的问题，如能回答，不胜感激！ Mr.Z @.*** &nbsp; … ------------------&nbsp; 原始邮件&nbsp; ------------------ 发件人: "yunqing-me/WatermarkDM" @.&gt;; 发送时间:&nbsp; 2023年6月28日(星期三) 下午4:33 @.&gt;; @.@.&gt;; 主题:&nbsp; Re: [yunqing-me/WatermarkDM] 跟不上df的工作了，出的比我学的快 (Issue #2) 你好，我有几个问题想请教你。 1.为什么使用哦个训练水印编码器/解码器命令的时候，无法读取到指定目录下的所有图片信息 2.在训练数据中嵌入二进制水印字符串的命令里，参数与py文件的参数对应不上呢 Thank you for your interest in our work. To address your issue, could you please provide necessary steps to reproduce the errors? Thanks. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented. Message ID: @.***&gt; 你好，对于你的问题： 是正常的。 为了加速计算FID Score, 50K real CIFAR-10 images的statistics会被提前计算并存在一个.npz file里面。 50K images会以batch_size=64进行读取，所以一共会有50k/64=782个batch。 bit_length 是一个预定义的args，应该是没有问题的。 谢谢指出，这个地方已经解决，请查看update。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented. Message ID: ***@***.***&gt;

你好，你可以成功复现代码么？能否指导一下我。我的邮箱1191496157@qq.com

**Comment by Middle-Night** [comment]
尊敬的作者，您好！ 感谢您的回复！ 在拜读您的论文《A Recipe for Watermarking Diffusion Models》后，我在进行实验项目代码的时候，遇到一点问题想咨询您一下。
对于文本到图像的扩散模型：
1.我在创建相关虚拟环境ldm的时候，遇到报错：“ERROR: File setup.py not found. Directory cannot be installed in editable mode: /root/autodl-tmp/WatermarkDM-main”。请问这该如何解决呢？
2.请问您训练该模型，使用到的数据集是什么呢？
如能解惑，不甚感激!
如有打扰，还请见谅！




Mr.Z
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mr.Z"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月29日(星期四) 上午8:44
***@***.***&gt;;

主题:&nbsp;回复：[yunqing-me/WatermarkDM] 跟不上df的工作了，出的比我学的快 (Issue #2)



感谢您为我解惑，您的回复给我极大的帮助！
祝您科研、事业一帆风顺！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月28日(周三) 下午5:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yunqing-me/WatermarkDM] 跟不上df的工作了，出的比我学的快 (Issue #2)




  
尊敬的作者，您好！ 感谢您的回复！ 我最近拜读您的论文《A Recipe for Watermarking Diffusion Models》，并在实验项目代码的时候，遇到一点问题想咨询您一下 1.第一张图片，输入命令行后，显示50000张图片计算出来的数据量为782，这个数字（可能我那个步骤不对）不知道得出来的是否正确。 2.第二张图片，命令行里的“bit length”参数无法识别。项目readme文件中说可能需要几个小时训练时间，但是我这边训练时间半小时就自动结束，而且结果未知。 3.第三张图片，命令行里的参数，与指定的python文件的参数，似乎对应不上，且强制修改命令行参数为指定python文件参数后，会被第四张图片里给定的路径覆盖掉。 以上就是我目前的项目进度以及遇到的问题，如能回答，不胜感激！ Mr.Z @.*** &nbsp;
 …
 ------------------ 原始邮件 ------------------ 发件人: "yunqing-me/WatermarkDM" @.&gt;; 发送时间: 2023年6月28日(星期三) 下午4:33 @.&gt;; @.@.&gt;; 主题: Re: [yunqing-me/WatermarkDM] 跟不上df的工作了，出的比我学的快 (Issue #2) 你好，我有几个问题想请教你。1.为什么使用哦个训练水印编码器/解码器命令的时候，无法读取到指定目录下的所有图片信息 2.在训练数据中嵌入二进制水印字符串的命令里，参数与py文件的参数对应不上呢 Thank you for your interest in our work. To address your issue, could you please provide necessary steps to reproduce the errors? Thanks. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
你好，对于你的问题：
  
是正常的。为了加速计算FID Score, 50K real CIFAR-10 images的statistics会被提前计算并存在一个.npz file里面。50K images会以batch_size=64进行读取，所以一共会有50k/64=782个batch。
 
bit_length 是一个预定义的args，应该是没有问题的。
 
谢谢指出，这个地方已经解决，请查看update。

**Comment by yunqing-me** [comment]
> 尊敬的作者，您好！ 感谢您的回复！ 在拜读您的论文《A Recipe for Watermarking Diffusion Models》后，我在进行实验项目代码的时候，遇到一点问题想咨询您一下。 对于文本到图像的扩散模型： 1.我在创建相关虚拟环境ldm的时候，遇到报错：“ERROR: File setup.py not found. Directory cannot be installed in editable mode: /root/autodl-tmp/WatermarkDM-main”。请问这该如何解决呢？ 2.请问您训练该模型，使用到的数据集是什么呢？ 如能解惑，不甚感激! 如有打扰，还请见谅！ Mr.Z ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Mr.Z" ***@***.***&gt;; 发送时间:&nbsp;2023年6月29日(星期四) 上午8:44 ***@***.***&gt;; 主题:&nbsp;回复：[yunqing-me/WatermarkDM] 跟不上df的工作了，出的比我学的快 (Issue #2) 感谢您为我解惑，您的回复给我极大的帮助！ 祝您科研、事业一帆风顺！
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年6月28日(周三) 下午5:33 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [yunqing-me/WatermarkDM] 跟不上df的工作了，出的比我学的快 (Issue #2) 尊敬的作者，您好！ 感谢您的回复！ 我最近拜读您的论文《A Recipe for Watermarking Diffusion Models》，并在实验项目代码的时候，遇到一点问题想咨询您一下 1.第一张图片，输入命令行后，显示50000张图片计算出来的数据量为782，这个数字（可能我那个步骤不对）不知道得出来的是否正确。 2.第二张图片，命令行里的“bit length”参数无法识别。项目readme文件中说可能需要几个小时训练时间，但是我这边训练时间半小时就自动结束，而且结果未知。 3.第三张图片，命令行里的参数，与指定的python文件的参数，似乎对应不上，且强制修改命令行参数为指定python文件参数后，会被第四张图片里给定的路径覆盖掉。 以上就是我目前的项目进度以及遇到的问题，如能回答，不胜感激！ Mr.Z @.*** &nbsp; … ------------------ 原始邮件 ------------------ 发件人: "yunqing-me/WatermarkDM" @.&gt;; 发送时间: 2023年6月28日(星期三) 下午4:33 @.&gt;; @.@.&gt;; 主题: Re: [yunqing-me/WatermarkDM] 跟不上df的工作了，出的比我学的快 (Issue #2) 你好，我有几个问题想请教你。1.为什么使用哦个训练水印编码器/解码器命令的时候，无法读取到指定目录下的所有图片信息 2.在训练数据中嵌入二进制水印字符串的命令里，参数与py文件的参数对应不上呢 Thank you for your interest in our work. To address your issue, could you please provide necessary steps to reproduce the errors? Thanks. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 你好，对于你的问题： 是正常的。为了加速计算FID Score, 50K real CIFAR-10 images的statistics会被提前计算并存在一个.npz file里面。50K images会以batch_size=64进行读取，所以一共会有50k/64=782个batch。 bit_length 是一个预定义的args，应该是没有问题的。 谢谢指出，这个地方已经解决，请查看update。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

请问您是Windows环境还是Linux？如果是Linux，请看一下https://github.com/CompVis/latent-diffusion

我们使用了同样的conda环境。
