### ISSUE TITLE
A question about watermarking stable diffusion model

### ISSUE THREAD

**Issue by njuaplusplus** [yunqing-me/WatermarkDM#5]
Why did you also train the text encoder? Is training the unet only unable to inject the watermark? Thanks.

**Comment by yunqing-me** [comment]
Thank you for your interest in our work.

Intuitively, since we add an `<image, text>` pair as the supervision signal, it is natural to fine-tuning the text encoder as well, similar to some few-shot text-to-image generators, e.g., DreamBooth.

Nevertheless, in general your idea is very interesting. We did not try to find minimum parameters to inject the watermark, in contrast, we find that we can maintain a good performance with low training cost in our setup. In this regard, finding **parameter-efficient way to inject watermark while maintaining high performance** could be the next research topic.
